<?php

namespace AppBundle\Repository;

/**
 * hopitauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hopitauxRepository extends \Doctrine\ORM\EntityRepository
{
}
