services:
#    doctors.example:
#        class: DoctorsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    service_education:
            class: DoctorsBundle\Controller\EducationsController
