hopitaux_index:
    path:     /
    defaults: { _controller: "AppBundle:hopitaux:index" }
    methods:  GET

hopitaux_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:hopitaux:show" }
    methods:  GET

hopitaux_new:
    path:     /new
    defaults: { _controller: "AppBundle:hopitaux:new" }
    methods:  [GET, POST]

hopitaux_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:hopitaux:edit" }
    methods:  [GET, POST]

hopitaux_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:hopitaux:delete" }
    methods:  DELETE
