<?php

namespace DoctorsBundle\Repository;

/**
 * CertificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificationsRepository extends \Doctrine\ORM\EntityRepository
{
}
