<?php

namespace DoctorsBundle\Repository;


use Symfony\Component\ClassLoader\ClassLoader;
use Doctrine\ORM\EntityManager;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    
   
    
}
        
