<?php

namespace DoctorsBundle\Repository;

/**
 * EducationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationsRepository extends \Doctrine\ORM\EntityRepository
{
}
