<?php

namespace DoctorsBundle\Repository;

/**
 * InvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoicesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSubServicesByDoctor($doctor, $service){

        $qb = $this->createQueryBuilder('i')
            ->select('i')
            ->innerJoin('i.subService', 's')
            ->where('i.doctor = :doctor')
            ->andWhere('s.service = :service')
            ->setParameter('service', $service)
            ->setParameter('doctor', $doctor);

        return $qb->getQuery()->getResult();
    }

    public function getSubServicesNoAddByDoctor($doctor, $service){

        $qb = $this->createQueryBuilder('i')
            ->select('i')
            ->innerJoin('i.subService', 's')
            ->andWhere('s.service = :service')
            ->setParameter('service', $service);

        return $qb->getQuery()->getResult();
    }
}
