<?php

namespace DoctorsBundle\Repository;
use Symfony\Component\Validator\Constraints\DateTime;


use Symfony\Component\ClassLoader\ClassLoader;
use Doctrine\ORM\EntityManager;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * LocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLocationBySeance($id){
        $qb = $this->createQueryBuilder('l')
            ->select('l')
            ->innerJoin('l.calendrie','c')
            ->innerJoin('c.seances','s')
            ->where('s.id = ?2')
            ->setMaxResults(1)
            ->setParameter(2, $id);
        return $qb->getQuery()->getResult();
    }

    public function delete($id) {
        $now =  (new \DateTime())->format('Y-m-d H:i:s');
        $qb = $this->createQueryBuilder('l')
            ->update('DoctorsBundle:Locations', 'l')
            ->set('l.deleatedAt', ':d')
            ->where('l.id = ?2')
            ->setParameter('d', $now)
            ->setParameter(2, $id);
        return $qb->getQuery()->getResult();
    }

    //A modifier la requete
    public function getCommentsByCity($city) {
        $entityManager = $this->getEntityManager();
        
        $rsm = new ResultSetMappingBuilder($entityManager);
        $rsm->addRootEntityFromClassMetadata('DoctorsBundle\Entity\Locations', 'l');

        
        $sql = "select {$rsm->generateSelectClause()}
                from locations as l 
                join doctors as d
                ON l.doctor_id = d.id
                where l.ville like '%{$city}%'";
        $query = $entityManager->createNativeQuery($sql, $rsm);

        $dataComments = $query->getResult();
        return $dataComments;
    }
         
    public function getCommentsByMaxRDV() {
        $entityManager = $this->getEntityManager();
        
        $rsm = new ResultSetMappingBuilder($entityManager);
        $rsm->addRootEntityFromClassMetadata('DoctorsBundle\Entity\Locations', 'l');

        
        $sql = "SELECT {$rsm->generateSelectClause()}
                from seances s 
                JOIN calendries c
                ON s.calendrie_id = c.id
                JOIN locations l
                ON c.location_id = l.id

                GROUP BY doctor_id
                order by COUNT(*) DESC
                LIMIT 0,6";
        $query = $entityManager->createNativeQuery($sql, $rsm);

        $dataComments = $query->getResult();
        return $dataComments;
    }

    public function getDoctorsByLonLat($lon,$lat){
        
        $entityManager = $this->getEntityManager();
        
        $rsm = new ResultSetMappingBuilder($entityManager, ResultSetMappingBuilder::COLUMN_RENAMING_INCREMENT);
        $rsm->addRootEntityFromClassMetadata('DoctorsBundle\Entity\Locations', 'l');

            $sql = "SELECT {$rsm->generateSelectClause()}
                    FROM locations l 
                    WHERE ACOS(SIN({$lat}) * sin(l.latitude) + cos({$lat}) * cos(l.latitude) * cos(l.langitude - ({$lon}))) * 6371 < 10000"
                    . " LIMIT 0,2";

        $query = $entityManager->createNativeQuery($sql, $rsm);

        $locations = $query->getResult();
        return $locations;
    }
    
    public function getNearestDoctorsByLonLat($lon,$lat){
        
        $entityManager = $this->getEntityManager();
        
        $rsm = new ResultSetMappingBuilder($entityManager, ResultSetMappingBuilder::COLUMN_RENAMING_INCREMENT);
        $rsm->addRootEntityFromClassMetadata('DoctorsBundle\Entity\Locations', 'l');

            $sql = "SELECT {$rsm->generateSelectClause()}
                    FROM locations l 
                    WHERE ACOS(SIN({$lat}) * sin(l.latitude) + cos({$lat}) * cos(l.latitude) * cos(l.langitude - ({$lon}))) * 6371 < 10000"
                    . " LIMIT 0,2";

        $query = $entityManager->createNativeQuery($sql, $rsm);

        $locations = $query->getResult();
        return $locations;
    }
    
    public function search($search_array) {
        $entityManager = $this->getEntityManager();
        $rsm = new ResultSetMappingBuilder($entityManager, ResultSetMappingBuilder::COLUMN_RENAMING_INCREMENT);
        $rsm->addRootEntityFromClassMetadata('DoctorsBundle\Entity\Locations', 'l');

        $sql = "SELECT {$rsm->generateSelectClause()}
                FROM locations l 
                LEFT JOIN doctors d
                ON l.doctor_id = d.id
                LEFT JOIN calendries c
                ON c.location_id = l.id
                LEFT JOIN invoices i
                ON i.doctor_id = d.id
                LEFT JOIN seances s
                ON s.calendrie_id = c.id
                LEFT JOIN doctors_specialities ds
                ON ds.doctor_id = d.id
                LEFT JOIN specialities sp
                ON sp.id = ds.specialitie_id
                LEFT JOIN services ser
                ON ser.specialitie_id = sp.id
                LEFT JOIN sub_services subS
                ON subS.service_id = ser.id
                WHERE 1=1 ";
                
        if(strcmp($search_array[0],"aucun") != 0){
            if (is_array($search_array) || is_object($search_array)){
                foreach($search_array as $mot){
                    $sql.=" AND (d.first_name like '%" . $mot . "%' or d.last_name     like '%" . $mot . "%' 
                           or l.adresse like '%" . $mot . "%' or l.ville like '%" . $mot . "%' 
                           or l.name like '%" . $mot . "%' or d.professional_statement like '%". $mot ."%'
                           or ser.service like '%". $mot ."%' or sp.libelle like '%". $mot ."%'
                           or subS.subService like '%". $mot ."%') "; 
                }
            }
        }
        $query = $entityManager->createNativeQuery($sql, $rsm);
        $locations = $query->getResult();
        return $locations;
    }
   
    public function searchBy($search_array, $specialite, $availability, $gender,
                             $fraisMin,$fraisMax, $timeMin, $timeMax) {
                                 
        if(is_array($availability[0])){
            foreach ($availability[0] as $day) {
                //get all days of next 2 mounth
                $dayDate  = date( 'Y-m-d', strtotime( 'next '.(string)$day ));
                $day2Date = date( 'Y-m-d', strtotime( $dayDate."+7 days" ));
                $day3Date = date( 'Y-m-d', strtotime( $day2Date."+7 days" ));
                $day4Date = date( 'Y-m-d', strtotime( $day3Date."+7 days" ));
                $day5Date = date( 'Y-m-d', strtotime( $day4Date."+7 days" ));
                $availabilityDate[] = $dayDate;
                $availabilityDate[] = $day2Date;
                $availabilityDate[] = $day3Date;
                $availabilityDate[] = $day4Date;
                $availabilityDate[] = $day5Date;
            }
            $availabilityDate = implode("','", $availabilityDate);
        }
        $entityManager = $this->getEntityManager();
        
        $rsm = new ResultSetMappingBuilder($entityManager, ResultSetMappingBuilder::COLUMN_RENAMING_INCREMENT);
        $rsm->addRootEntityFromClassMetadata('DoctorsBundle\Entity\Locations', 'l');

        
        $sql = "SELECT {$rsm->generateSelectClause()}
                FROM locations l 
                LEFT JOIN doctors d
                ON l.doctor_id = d.id
                LEFT JOIN calendries c
                ON c.location_id = l.id
                LEFT JOIN invoices i
                ON i.doctor_id = d.id
                LEFT JOIN seances s
                ON s.calendrie_id = c.id
                LEFT JOIN doctors_specialities ds
                ON ds.doctor_id = d.id
                LEFT JOIN specialities sp
                ON sp.id = ds.specialitie_id
                LEFT JOIN services ser
                ON ser.specialitie_id = sp.id
                LEFT JOIN sub_services subS
                ON subS.service_id = ser.id
                WHERE 1=1 ";
                
        if(strcmp($gender, "'mr'") == 0){
            $sql.= " AND d.title = 'mr' ";
        }elseif(strcmp($gender, "'mme','mlle'") == 0){
            $sql.= " AND d.title IN ({$gender}) ";
        }
        
        if(is_array($availability[0])){
            $sql.=" AND c.date IN ('{$availabilityDate}') "; 
        }
        if(strcmp($specialite,"aucun") != 0){
            $sql.=" AND sp.libelle = '{$specialite}' "; 
        }
        if(strcmp($timeMin,"1:00:00") != 0 || strcmp($timeMax,"1:00:00") != 0){
            $sql.= " AND s.heur_debut BETWEEN '{$timeMin}' AND '{$timeMax}' AND s.heur_fin BETWEEN '{$timeMin}' AND '{$timeMax}' ";
        }

        if(strcmp($fraisMin,"0") != 0 || strcmp($fraisMax,"0") != 0){
            $sql.= " AND i.price BETWEEN '{$fraisMin}' AND '{$fraisMax}' ";
        }
        
        if(strcmp($search_array[0],"aucun") != 0){
            if (is_array($search_array) || is_object($search_array)){
                foreach($search_array as $mot){
                    $sql.=" AND (d.first_name like '%" . $mot . "%' or d.last_name     like '%" . $mot . "%' 
                           or l.adresse like '%" . $mot . "%' or l.ville like '%" . $mot . "%' 
                           or l.name like '%" . $mot . "%' or d.professional_statement like '%". $mot ."%'
                           or ser.service like '%". $mot ."%' or sp.libelle like '%". $mot ."%'
                           or subS.subService like '%". $mot ."%') "; 
                }
            }
        }
        $query = $entityManager->createNativeQuery($sql, $rsm);

        $locations = $query->getResult();
        
        return $locations;
    }
    
}