<?php

namespace DoctorsBundle\Repository;

/**
 * ServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getServicesByDoctor($doctor){

        $qb = $this->createQueryBuilder('s')
            ->select('s')
            ->innerJoin('s.subServices', 'sub_services')
            ->innerJoin('sub_services.invoices', 'i')
            ->where('i.doctor = :doctor')
            ->setParameter('doctor', $doctor);

        return $qb->getQuery()->getResult();
    }
}
