<?php

namespace DoctorsBundle\Repository;

/**
 * SocialInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
