<?php

namespace DoctorsBundle\Repository;

/**
 * SpecialitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialitiesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTestSpecialitieByDoctor($specialitie, $doctor){
        $qb = $this->createQueryBuilder('s')
            ->select('s');
        $qb->innerJoin('s.doctors', 'd');
        $qb->where('d.id = :doctor')
            ->setParameter('doctor', $doctor);
        $qb->andWhere('s.id = :specialitie')
            ->setParameter('specialitie', $specialitie);
        return $qb->getQuery()->getResult();
    }

    public function getSpecialitiesByDoctor($doctor){
        $qb = $this->createQueryBuilder('s')
            ->select('s');
        $qb->innerJoin('s.doctors', 'd');
        $qb->where('d.id = :doctor')
            ->setParameter('doctor', $doctor);
        return $qb->getQuery()->getResult();
    }
}
