<?php

namespace DoctorsBundle\Repository;

/**
 * SubServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubServicesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSubServicesByDoctor($doctor){

        $qb = $this->createQueryBuilder('s')
            ->select('s')
            ->innerJoin('s.invoices', 'i')
            ->where('i.doctor = :doctor')
            ->setParameter('doctor', $doctor);

        return $qb->getQuery()->getResult();
    }
}
