<?php

namespace AppointmentsBundle\Repository;

/**
 * AppointementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointementsRepository extends \Doctrine\ORM\EntityRepository
{

}
