<?php

namespace AppointmentsBundle\Repository;

/**
 * AppointmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAppointmentsOfToday($user){
        $today = date('Y-m-d');
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->innerJoin('a.seance', 's')
            ->innerJoin('s.calendrie', 'c')
            ->where('c.date = :today')
            ->andWhere('a.patient = :patient')
            ->setParameter('today', $today)
            ->setParameter('patient', $user);
        return $qb->getQuery()->getResult();
    }
    public function getAppointmentsOfNextDays($user){
        $today = date('Y-m-d');
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->innerJoin('a.seance', 's')
            ->innerJoin('s.calendrie', 'c')
            ->where('c.date > :today')
            ->andWhere('a.patient = :patient')
            ->setParameter('today', $today)
            ->setParameter('patient', $user);
        return $qb->getQuery()->getResult();
    }
    public function getAppointmentsOfLastDays($user){
        $today = date('Y-m-d');
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->innerJoin('a.seance', 's')
            ->innerJoin('s.calendrie', 'c')
            ->where('c.date < :today')
            ->andWhere('a.patient = :patient')
            ->setParameter('today', $today)
            ->setParameter('patient', $user);
        return $qb->getQuery()->getResult();
    }

    public function cancel($id){
        $qb = $this->createQueryBuilder('a')
            ->update('AppointmentsBundle:Appointments', 'a')
            ->set('a.etat', ':d')
            ->where('a.id = ?2')
            ->setParameter('d', 'annuler')
            ->setParameter(2, $id);
        return $qb->getQuery()->getResult();
    }


}
