<?php

namespace AppointmentsBundle\Repository;

/**
 * ReasonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReasonsRepository extends \Doctrine\ORM\EntityRepository
{
}
