<?php

namespace AppointmentsBundle\Repository;
use Doctrine\ORM\Query;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * SeancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeancesRepository extends \Doctrine\ORM\EntityRepository
{
    public function disponibilite($seance, $dispo){

        $qb = $this->createQueryBuilder('s')
            ->update('AppointmentsBundle:Seances', 's')
            ->set('s.dispo', ':d')
            ->where('s.id = ?2')
            ->setParameter('d', $dispo)
            ->setParameter(2, $seance);
        return $qb->getQuery()->getResult();
    }

    public function verifierHeurDebut($heurDebut, $calendrie, $heurFin, $doctor){

        $qb = $this->createQueryBuilder('s')
            ->select('s')
            ->innerJoin('s.calendrie', 'c')
            ->innerJoin('c.location', 'l')
            ->innerJoin('l.doctor', 'd')
            ->where('s.heurDebut BETWEEN :heurDebut AND :heurFin')
            ->andWhere('l.doctor = :doctor')
            ->andWhere('c.date LIKE :calendrie')
            ->setParameter('calendrie', $calendrie)
            ->setParameter('heurFin', $heurFin)
            ->setParameter('doctor', $doctor)
            ->setParameter('heurDebut', $heurDebut);

        return $qb->getQuery()->getResult();
    }


    public function getSeacesByCalendar($calendar){

        $qb = $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.calendrie = :calendrie')
            ->setParameter('calendrie', $calendar)
            ->orderBy('s.heurDebut');

        return $qb->getQuery()->getResult();
    }


}
