certifications_index:
    path:     /
    defaults: { _controller: "DoctorsBundle:Certifications:index" }
    methods:  GET

certifications_show:
    path:     /{id}/show
    defaults: { _controller: "DoctorsBundle:Certifications:show" }
    methods:  GET

certifications_new:
    path:     /new
    defaults: { _controller: "DoctorsBundle:Certifications:new" }
    methods:  [GET, POST]

certifications_addCertification:
    path:     /addCertification
    defaults: { _controller: "DoctorsBundle:Certifications:addCertification" }

certifications_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorsBundle:Certifications:edit" }
    methods:  [GET, POST]

certifications_delete:
    path:     /{certification}/delete
    defaults: { _controller: "DoctorsBundle:Certifications:delete" }
