subservices_index:
    path:     /
    defaults: { _controller: "DoctorsBundle:SubServices:index" }
    methods:  GET

subservices_comboSubServicesByService:
    path:     /{service}/comboSubServices
    defaults: { _controller: "DoctorsBundle:SubServices:comboSubServicesByService" }

subservices_show:
    path:     /{id}/show
    defaults: { _controller: "DoctorsBundle:SubServices:show" }
    methods:  GET

subservices_new:
    path:     /new
    defaults: { _controller: "DoctorsBundle:SubServices:new" }
    methods:  [GET, POST]

subservices_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorsBundle:SubServices:edit" }
    methods:  [GET, POST]

subservices_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorsBundle:SubServices:delete" }
    methods:  DELETE
